In [52]:
import pandas as pd 
import sklearn

In [53]:
df = pd.read_csv('bbc-text.csv')

In [54]:
df

           category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
...             ...                                                ...
2220       business  cars pull down us retail figures us retail sal...
2221       politics  kilroy unveils immigration policy ex-chatshow ...
2222  entertainment  rem announce new glasgow concert us band rem h...
2223       politics  how political squabbles snowball it s become c...
2224          sport  souness delight at euro progress boss graeme s...

[2225 rows x 2 columns]

In [55]:
df['category'].unique()

array(['tech', 'business', 'sport', 'entertainment', 'politics'],
      dtype=object)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2225 entries, 0 to 2224
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  2225 non-null   object
 1   text      2225 non-null   object
dtypes: object(2)
memory usage: 34.9+ KB

### Writing a function performing TEXT cleaning before vectorization

In [57]:
import pandas as pd 
import re
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def text_cleaning(text):
    text = text.lower()
    # lowercase 

    text = re.sub('[^a-zA-Z\s]','',text)
    #removing special characters

    words = text.split()
    #tokenization

    words = [word for word in words if word not in stop_words]
    # removing stopwords

    words = [lemmatizer.lemmatize(word) for word in words]
    # lemmatization 

    return ' '.join(words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\saich\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\saich\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\saich\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\saich\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\saich\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [58]:
df['cleaned_text'] = df['text'].apply(text_cleaning) # applying cleaning function to features

In [59]:
df

,category,text,cleaned_text
0,tech,tv future in the hands of viewers with home th...,tv future hand viewer home theatre system plas...
1,business,worldcom boss left books alone former worldc...,worldcom bos left book alone former worldcom b...
2,sport,tigers wary of farrell gamble leicester say ...,tiger wary farrell gamble leicester say rushed...
3,sport,yeading face newcastle in fa cup premiership s...,yeading face newcastle fa cup premiership side...
4,entertainment,ocean s twelve raids box office ocean s twelve...,ocean twelve raid box office ocean twelve crim...
...,...,...,...
2220,business,cars pull down us retail figures us retail sal...,car pull u retail figure u retail sale fell ja...
2221,politics,kilroy unveils immigration policy ex-chatshow ...,kilroy unveils immigration policy exchatshow h...
2222,entertainment,rem announce new glasgow concert us band rem h...,rem announce new glasgow concert u band rem an...
2223,politics,how political squabbles snowball it s become c...,political squabble snowball become commonplace...
2224,sport,souness delight at euro progress boss graeme s...,souness delight euro progress bos graeme soune...

## Step 1- Splitting inputs (X) and output (y)

In [60]:
# indentifying our target variable and splitting Inputs(features) X and Output y

In [61]:
X = df['cleaned_text']
y = df['category']

In [62]:
X

0       tv future hand viewer home theatre system plas...
1       worldcom bos left book alone former worldcom b...
2       tiger wary farrell gamble leicester say rushed...
3       yeading face newcastle fa cup premiership side...
4       ocean twelve raid box office ocean twelve crim...
                              ...
2220    car pull u retail figure u retail sale fell ja...
2221    kilroy unveils immigration policy exchatshow h...
2222    rem announce new glasgow concert u band rem an...
2223    political squabble snowball become commonplace...
2224    souness delight euro progress bos graeme soune...
Name: cleaned_text, Length: 2225, dtype: object

In [63]:
y

0                tech
1            business
2               sport
3               sport
4       entertainment
            ...
2220         business
2221         politics
2222    entertainment
2223         politics
2224            sport
Name: category, Length: 2225, dtype: object

## Step 2- Splitting the data into TEST(X_train, y_train) and TRAIN(X_test)

In [64]:
# As we cannot pass the actual/whole data directly to the model we are Splitting TEST(X_train, y_train) and TRAIN(X_test) data with 80-20 ratio

In [65]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.8,random_state=45)

In [66]:
X_train

1734    disney back sony dvd technology next generatio...
1772    athens memory soar low well goodbye another ol...
575     movie body hit peertopeer net movie industry s...
984     music mogul fuller sell company pop idol supre...
1264    poll explains freekick decision referee graham...
                              ...
580     napster offer rented music go music downloadin...
163     musical treatment capra film classic film wond...
607     swap offer pirated window xp computer giant mi...
1916    wine comedy win critic award quirky comedy sid...
1667    broadband uk gather pace one person uk joining...
Name: cleaned_text, Length: 1780, dtype: object

In [67]:
X_train.dtypes

dtype('O')

In [68]:
y_train

1734             tech
1772            sport
575              tech
984     entertainment
1264            sport
            ...
580              tech
163     entertainment
607              tech
1916    entertainment
1667             tech
Name: category, Length: 1780, dtype: object

In [69]:
X_test

1371    concern school diploma plan final appeal made ...
1266    blunkett row end blair prime minister tony bla...
875     sun offer processing hour sun microsystems lau...
2046    tory expert denies defeatism conservative camp...
819     mobile gaming take india gaming move one faste...
                              ...
1387    parker saxophone head auction saxophone belong...
736     sullivan keep powder dry gunning glory ultimat...
1063    house price drop sale slow house price fell no...
1496    klinsmann issue lehmann warning germany coach ...
2213    progress new internet domain early net could t...
Name: cleaned_text, Length: 445, dtype: object

In [70]:
y_test

1371         politics
1266         politics
875              tech
2046         politics
819              tech
            ...
1387    entertainment
736             sport
1063         business
1496            sport
2213             tech
Name: category, Length: 445, dtype: object

## Step 3 - Vectorization

#### Transforming corpus to DTM (Document-Term Matrix)

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer

TFIDF = TfidfVectorizer(max_features=5000)
X_train_trans = TFIDF.fit_transform(X_train)

In [72]:
X_train_trans.shape

(1780, 5000)

## Step 3.5 - Feature Engineering on Target y_train

In [73]:
# as y_train is in categorical form we are encoding it using Label encoding

In [74]:
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

y_train_trans = LE.fit_transform(y_train)

In [75]:
y_train_trans

array([4, 3, 4, ..., 4, 1, 4], shape=(1780,))

In [76]:
y_train_trans

array([4, 3, 4, ..., 4, 1, 4], shape=(1780,))

## Step 4- Model training using Algorithmn X_test_trans and y_train

In [77]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train_trans,y_train_trans)

KNeighborsClassifier()

## Step 5 - Vectorization and Feature engineering on Test data

In [78]:
X_test_trans = TFIDF.transform(X_test)

In [79]:
X_test_trans

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 53737 stored elements and shape (445, 5000)>

In [80]:
y_test_trans = LE.transform(y_test)

In [81]:
y_test_trans

array([2, 2, 4, 2, 4, 3, 0, 2, 1, 1, 3, 0, 0, 2, 4, 1, 3, 2, 2, 2, 4, 0,
       0, 2, 2, 2, 3, 3, 4, 1, 4, 0, 3, 3, 3, 2, 2, 0, 0, 4, 3, 4, 0, 0,
       0, 0, 0, 0, 1, 3, 0, 4, 3, 0, 3, 2, 0, 0, 2, 0, 1, 3, 0, 2, 3, 3,
       0, 2, 0, 3, 0, 2, 4, 1, 3, 0, 0, 4, 1, 4, 1, 4, 0, 0, 2, 3, 3, 3,
       4, 0, 3, 4, 3, 3, 4, 4, 1, 2, 3, 1, 1, 1, 2, 1, 0, 2, 1, 4, 1, 2,
       3, 1, 2, 3, 4, 4, 0, 0, 0, 1, 3, 3, 4, 0, 3, 3, 3, 0, 1, 3, 2, 0,
       3, 3, 3, 0, 3, 0, 1, 0, 1, 1, 0, 1, 2, 3, 3, 3, 0, 4, 1, 3, 3, 3,
       0, 4, 0, 2, 0, 4, 4, 4, 0, 4, 2, 3, 2, 4, 1, 2, 1, 2, 0, 1, 1, 3,
       2, 4, 0, 0, 4, 0, 3, 1, 3, 3, 0, 2, 4, 2, 1, 3, 0, 2, 1, 3, 0, 3,
       4, 1, 0, 4, 2, 0, 2, 2, 2, 0, 3, 2, 3, 4, 1, 0, 0, 2, 0, 4, 1, 1,
       3, 0, 3, 3, 3, 4, 3, 3, 0, 0, 0, 3, 2, 2, 3, 1, 2, 3, 3, 3, 4, 2,
       3, 3, 4, 2, 4, 1, 2, 1, 2, 4, 3, 0, 2, 3, 3, 3, 2, 1, 0, 3, 4, 2,
       3, 0, 4, 1, 1, 2, 4, 2, 3, 0, 1, 0, 4, 0, 2, 1, 2, 2, 3, 0, 0, 3,
       3, 3, 3, 0, 3, 4, 4, 3, 1, 3, 0, 3, 4, 4, 4, 2, 2, 0, 4, 0, 0, 3,
       2, 1, 4, 0, 1, 0, 2, 1, 3, 2, 2, 3, 2, 4, 2, 0, 2, 1, 4, 1, 0, 3,
       4, 1, 3, 2, 4, 4, 3, 3, 2, 2, 3, 0, 3, 4, 4, 4, 0, 3, 3, 3, 1, 3,
       4, 0, 2, 3, 4, 4, 0, 0, 0, 3, 0, 0, 1, 4, 3, 0, 4, 0, 1, 1, 2, 2,
       1, 4, 3, 2, 2, 0, 1, 1, 2, 3, 3, 0, 0, 4, 4, 4, 0, 2, 0, 0, 2, 2,
       3, 1, 4, 1, 3, 3, 4, 2, 4, 1, 2, 0, 3, 0, 3, 0, 4, 3, 4, 3, 4, 4,
       2, 0, 2, 1, 1, 4, 0, 2, 2, 0, 4, 0, 3, 3, 3, 0, 3, 3, 3, 1, 1, 0,
       1, 3, 0, 3, 4])

## Step 6 - Prediction on X_test_trans

#### here we are pasing our test inputs (X_test_trans) to the model to get our prediction output(y_pred)

In [82]:
y_pred =  model.predict(X_test_trans)

In [83]:
y_pred

array([2, 2, 2, 2, 4, 3, 0, 2, 1, 1, 3, 0, 0, 2, 4, 1, 3, 2, 2, 2, 4, 0,
       0, 2, 2, 2, 3, 3, 4, 1, 4, 0, 3, 3, 3, 2, 2, 0, 0, 2, 3, 4, 2, 0,
       0, 0, 0, 4, 1, 3, 0, 4, 3, 0, 3, 2, 0, 0, 2, 0, 1, 3, 2, 2, 3, 3,
       2, 2, 0, 3, 0, 2, 4, 1, 3, 0, 0, 4, 2, 4, 1, 4, 0, 2, 2, 3, 3, 3,
       4, 0, 3, 4, 3, 3, 4, 4, 1, 2, 3, 1, 1, 1, 2, 1, 0, 2, 1, 4, 2, 2,
       3, 1, 2, 3, 4, 4, 0, 2, 0, 1, 3, 3, 4, 0, 3, 3, 3, 0, 1, 3, 2, 0,
       3, 3, 3, 0, 3, 0, 1, 0, 1, 1, 0, 1, 2, 3, 3, 3, 0, 2, 1, 3, 3, 3,
       0, 4, 0, 2, 0, 4, 4, 4, 0, 4, 2, 3, 0, 4, 3, 2, 1, 4, 0, 1, 1, 3,
       2, 4, 0, 0, 4, 0, 3, 1, 3, 3, 0, 2, 4, 2, 1, 3, 0, 2, 1, 3, 0, 3,
       4, 1, 0, 4, 2, 0, 2, 2, 2, 0, 3, 2, 3, 4, 1, 2, 0, 2, 0, 4, 1, 1,
       3, 1, 3, 3, 3, 2, 3, 3, 0, 0, 0, 3, 2, 2, 3, 1, 2, 3, 3, 3, 4, 2,
       3, 3, 4, 2, 4, 1, 2, 1, 2, 4, 3, 0, 2, 3, 3, 3, 2, 1, 0, 3, 4, 2,
       3, 2, 4, 1, 1, 2, 4, 2, 3, 0, 1, 0, 4, 0, 2, 1, 2, 2, 3, 0, 0, 3,
       3, 3, 3, 0, 3, 1, 4, 3, 1, 3, 0, 3, 4, 4, 4, 2, 2, 0, 4, 0, 0, 3,
       2, 1, 4, 0, 3, 0, 2, 1, 3, 2, 2, 3, 2, 1, 2, 0, 2, 1, 4, 1, 4, 3,
       4, 1, 3, 2, 4, 4, 3, 3, 2, 2, 3, 0, 3, 4, 4, 4, 0, 3, 3, 3, 1, 3,
       4, 2, 2, 3, 4, 4, 0, 0, 0, 3, 0, 0, 1, 4, 3, 0, 4, 0, 1, 1, 2, 1,
       1, 4, 3, 2, 2, 0, 1, 1, 2, 3, 3, 0, 0, 4, 4, 2, 0, 2, 4, 0, 2, 2,
       3, 1, 4, 1, 3, 3, 4, 2, 4, 1, 2, 4, 3, 0, 3, 0, 4, 3, 4, 3, 4, 4,
       2, 0, 2, 2, 4, 4, 0, 2, 4, 4, 0, 0, 3, 3, 3, 0, 3, 3, 3, 1, 1, 2,
       1, 3, 0, 3, 4])

## Step 7 Passing y-test(actual) and y_pred(model_prediction) to evaluation metrics

#### in this step we are passing our actual target variable and model prediction to evaluation metrics 
- To check how accurate our model is performing

In [84]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test_trans,y_pred)

In [85]:
score

0.9258426966292135

this shows are model is performing 74% accurately

## Saving Production files

In [86]:
import joblib 
joblib.dump({'model':model,'TFIDF':TFIDF,'Label_encod':LE},'text_model.pkl')

['text_model.pkl']

In [87]:
text_model = joblib.load('text_model.pkl')

In [88]:
text_model['TFIDF']

TfidfVectorizer(max_features=5000)

In [89]:
text_model['Label_encod']

LabelEncoder()

In [90]:
text_model['model']

KNeighborsClassifier()